StephanK83/AllShare

Gemfile.lock, app/models/item.rb, db/migrate/20230307125833_create_items.rb, db/migrate/20230307195149_add_extra_info_item.rb, db/schema.rb, test/models/item_test.rb
=> Item model is created

Gemfile.lock, app/models/booking.rb, db/migrate/20230307124030_create_bookings.rb, db/schema.rb, test/models/booking_test.rb
Guys, the booking model is done. Please check it
=> booking model is created

Gemfile.lock, db/migrate/20230307175756_add_user_information.rb, db/schema.rb
Migration for the user
- first name
- last name
- street name
- postal code
- city
- country
- phone
=> added user info to the db

app/models/booking.rb, app/models/user.rb
question about the association between the User and Review
=> booking and user model association update

config/routes.rb
We created all the routes, will limit the actions in a second moment
=> routes created, need to limit it later

Gemfile, Gemfile.lock, app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/items_controller.rb, app/models/booking.rb, app/models/item.rb, app/models/user.rb, app/policies/application_policy.rb, app/policies/booking_policy.rb, app/policies/item_policy.rb, app/views/bookings/edit.html.erb, app/views/bookings/index.html.erb, app/views/bookings/new.html.erb, app/views/bookings/show.html.erb, app/views/items/edit.html.erb, app/views/items/index.html.erb, app/views/items/new.html.erb, app/views/items/show.html.erb, app/views/pages/home.html.erb, config/routes.rb, test/controllers/bookings_controller_test.rb, test/controllers/items_controller_test.rb, test/policies/booking_policy_test.rb, test/policies/item_policy_test.rb
Authorization work in progress
=> Items Bookings controllers in progress

app/controllers/application_controller.rb, app/controllers/bookings_controller.rb, app/controllers/items_controller.rb, app/policies/item_policy.rb, app/views/bookings/index.html.erb, app/views/devise/registrations/edit.html.erb, app/views/devise/registrations/new.html.erb, app/views/items/my_items.html.erb, app/views/pages/home.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
Bookings Controller updates: edit / update
Booking Index View: more info about the booking
Navbar: logo(root_path) / avatar(first_name + My bookings + My items)
=> backend small updates

app/controllers/bookings_controller.rb, app/controllers/items_controller.rb, app/controllers/reviews_controller.rb, app/helpers/application_helper.rb, app/models/booking.rb, app/models/item.rb, app/policies/review_policy.rb, app/views/bookings/index.html.erb, app/views/items/show.html.erb, app/views/reviews/_review.html.erb, app/views/reviews/new.html.erb, config/routes.rb, db/migrate/20230310162419_add_item_to_reviews.rb, db/schema.rb, test/controllers/reviews_controller_test.rb, test/policies/review_policy_test.rb
Still missing:
edit / update / destroy methods
=> review the item through booking

app/controllers/chatrooms_controller.rb, app/controllers/messages_controller.rb, app/policies/chatroom_policy.rb, app/policies/message_policy.rb, app/views/items/index.html.erb, app/views/items/my_items.html.erb, test/policies/chatroom_policy_test.rb, test/policies/message_policy_test.rb
updates:
- button (List an item) on several pages
- authorization policy for chatroom & message
=> misc updates

.gitignore, Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/models/item.rb, app/views/items/edit.html.erb, app/views/items/index.html.erb, app/views/items/my_favorite_items.html.erb, app/views/items/my_items.html.erb, app/views/items/new.html.erb, app/views/items/show.html.erb, config/environments/development.rb, config/storage.yml, db/migrate/20230313131417_create_active_storage_tables.active_storage.rb, db/schema.rb
trying to update the connections for the model / controller / index page / edit page
=> cloudinary in progress

app/views/items/new.html.erb
'Film & photography', 'Audio & visual', 'Projectors & screens', 'Drones', 'DJ equipment', 'Storage', 'Electronics', 'Transport', 'Party & Events', 'Sports', 'Home, office & garden', 'Clothing', 'Holiday & travel', 'Musical instruments', 'Kids & baby'
=> categories dropdown list

app/controllers/pages_controller.rb, app/views/pages/about_us.html.erb, app/views/pages/how_it_works.html.erb, app/views/shared/_footer.html.erb, app/views/shared/_navbar.html.erb, config/routes.rb
About us & How it works pages are created and they are available in the footer.
How it works page is displayed also in the navbar
=> AboutUs & HowItWorks pages

app/views/items/my_items.html.erb
Fixed the image tag in the My Items page
=> fix image tage in the My Items page

app/assets/stylesheets/components/_footer.scss, app/views/shared/_footer.html.erb
some changes in the footer. Move subscription folder. 
Draft, not finished.
=> removed bullet points in footer

app/views/layouts/application.html.erb, app/views/pages/home.html.erb, app/views/shared/_home_navbar.html.erb, app/views/shared/_navbar.html.erb
Change font colors in the navbar
=> Navbardesignimproval

app/views/items/index.html.erb, app/views/layouts/application.html.erb
=> Heartsoncards

app/assets/stylesheets/pages/_about_us.scss, app/assets/stylesheets/pages/_button.scss, app/assets/stylesheets/pages/_how_it_works.scss, app/models/item.rb, app/test/button.css, app/test/button.html, app/views/items/show.html.erb, app/views/pages/button.html.erb
please check the item show page layout thanks
=> item show page

app/views/pages/how_it_works.html.erb
we can add a small video about how it works - just another idea
=> Video works

app/views/reviews/_review.html.erb, app/views/reviews/new.html.erb
Added golden stars in the review page.
=> Layoutfixreviews

Gemfile, Gemfile.lock, app/controllers/items_controller.rb, app/javascript/controllers/index.js, app/javascript/controllers/map_controller.js, app/models/item.rb, app/views/items/_popup.html.erb, app/views/items/index.html.erb, app/views/layouts/application.html.erb, config/initializers/geocoder.rb, db/migrate/20230321163038_add_coordinates_to_items.rb, db/schema.rb
=> Mapbox feature

app/javascript/controllers/index.js, app/views/shared/_home_navbar.html.erb
message chatroom link works now
deleted show_map_button.js <-- not needed anymore
=> fixed issues

app/controllers/bookings_controller.rb, app/javascript/controllers/map_controller.js, app/views/bookings/index.html.erb, db/seeds.rb
=> Booking index

app/views/bookings/new.html.erb, app/views/items/index.html.erb, app/views/items/show.html.erb, app/views/shared/_navbar.html.erb
Reverts StephanK83/AllShare#103
=> Revert "Somefixesbookingsnewpage"
